# Application Name
spring.application.name=lab4_withdto

# H2 Database Configuration
# File-based database (persists data to disk)
spring.datasource.url=jdbc:h2:file:./data/lab4_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (enable for debugging - optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
# Server Port
server.port=8080

# Optional: Logging
logging.level.root=WARN
logging.level.com.ihit.lab4=DEBUG

# CORS Configuration
spring.web.cors.allowedOrigins=http://localhost:4200,https://my-app-w11-12.azurewebsites.net
spring.web.cors.allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowedHeaders=*
spring.web.cors.allowCredentials=true

